//   Copyright 2023 Paul Borman
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.

package proc

// #include <unistd.h>
import "C"

// Sysconf is the POSIX Sysconf function.
func Sysconf(name SCName) int64 {
	return int64(C.sysconf(C.int(name)))
}

// An SCName represents a name for the POSIX Sysconf function call.
type SCName int

// Known names for sysconf
const (
	SCArgMax                     = SCName(C._SC_ARG_MAX)
	SCChildMax                   = SCName(C._SC_CHILD_MAX)
	SCClkTck                     = SCName(C._SC_CLK_TCK)
	SCNgroupsMax                 = SCName(C._SC_NGROUPS_MAX)
	SCOpenMax                    = SCName(C._SC_OPEN_MAX)
	SCStreamMax                  = SCName(C._SC_STREAM_MAX)
	SCTznameMax                  = SCName(C._SC_TZNAME_MAX)
	SCJobControl                 = SCName(C._SC_JOB_CONTROL)
	SCSavedIds                   = SCName(C._SC_SAVED_IDS)
	SCRealtimeSignals            = SCName(C._SC_REALTIME_SIGNALS)
	SCPriorityScheduling         = SCName(C._SC_PRIORITY_SCHEDULING)
	SCTimers                     = SCName(C._SC_TIMERS)
	SCAsynchronousIo             = SCName(C._SC_ASYNCHRONOUS_IO)
	SCPrioritizedIo              = SCName(C._SC_PRIORITIZED_IO)
	SCSynchronizedIo             = SCName(C._SC_SYNCHRONIZED_IO)
	SCFsync                      = SCName(C._SC_FSYNC)
	SCMappedFiles                = SCName(C._SC_MAPPED_FILES)
	SCMemlock                    = SCName(C._SC_MEMLOCK)
	SCMemlockRange               = SCName(C._SC_MEMLOCK_RANGE)
	SCMemoryProtection           = SCName(C._SC_MEMORY_PROTECTION)
	SCMessagePassing             = SCName(C._SC_MESSAGE_PASSING)
	SCSemaphores                 = SCName(C._SC_SEMAPHORES)
	SCSharedMemoryObjects        = SCName(C._SC_SHARED_MEMORY_OBJECTS)
	SCAioListioMax               = SCName(C._SC_AIO_LISTIO_MAX)
	SCAioMax                     = SCName(C._SC_AIO_MAX)
	SCAioPrioDeltaMax            = SCName(C._SC_AIO_PRIO_DELTA_MAX)
	SCDelaytimerMax              = SCName(C._SC_DELAYTIMER_MAX)
	SCMqOpenMax                  = SCName(C._SC_MQ_OPEN_MAX)
	SCMqPrioMax                  = SCName(C._SC_MQ_PRIO_MAX)
	SCVersion                    = SCName(C._SC_VERSION)
	SCPagesize                   = SCName(C._SC_PAGESIZE)
	SCRtsigMax                   = SCName(C._SC_RTSIG_MAX)
	SCSemNsemsMax                = SCName(C._SC_SEM_NSEMS_MAX)
	SCSemValueMax                = SCName(C._SC_SEM_VALUE_MAX)
	SCSigqueueMax                = SCName(C._SC_SIGQUEUE_MAX)
	SCTimerMax                   = SCName(C._SC_TIMER_MAX)
	SCBcBaseMax                  = SCName(C._SC_BC_BASE_MAX)
	SCBcDimMax                   = SCName(C._SC_BC_DIM_MAX)
	SCBcScaleMax                 = SCName(C._SC_BC_SCALE_MAX)
	SCBcStringMax                = SCName(C._SC_BC_STRING_MAX)
	SCCollWeightsMax             = SCName(C._SC_COLL_WEIGHTS_MAX)
	SCEquivClassMax              = SCName(C._SC_EQUIV_CLASS_MAX)
	SCExprNestMax                = SCName(C._SC_EXPR_NEST_MAX)
	SCLineMax                    = SCName(C._SC_LINE_MAX)
	SCReDupMax                   = SCName(C._SC_RE_DUP_MAX)
	SCCharclassNameMax           = SCName(C._SC_CHARCLASS_NAME_MAX)
	SC2Version                   = SCName(C._SC_2_VERSION)
	SC2CBind                     = SCName(C._SC_2_C_BIND)
	SC2CDev                      = SCName(C._SC_2_C_DEV)
	SC2FortDev                   = SCName(C._SC_2_FORT_DEV)
	SC2FortRun                   = SCName(C._SC_2_FORT_RUN)
	SC2SwDev                     = SCName(C._SC_2_SW_DEV)
	SC2Localedef                 = SCName(C._SC_2_LOCALEDEF)
	SCPii                        = SCName(C._SC_PII)
	SCPiiXti                     = SCName(C._SC_PII_XTI)
	SCPiiSocket                  = SCName(C._SC_PII_SOCKET)
	SCPiiInternet                = SCName(C._SC_PII_INTERNET)
	SCPiiOsi                     = SCName(C._SC_PII_OSI)
	SCPoll                       = SCName(C._SC_POLL)
	SCSelect                     = SCName(C._SC_SELECT)
	SCUioMaxiov                  = SCName(C._SC_UIO_MAXIOV)
	SCIovMax                     = SCName(C._SC_IOV_MAX)
	SCPiiInternetStream          = SCName(C._SC_PII_INTERNET_STREAM)
	SCPiiInternetDgram           = SCName(C._SC_PII_INTERNET_DGRAM)
	SCPiiOsiCots                 = SCName(C._SC_PII_OSI_COTS)
	SCPiiOsiClts                 = SCName(C._SC_PII_OSI_CLTS)
	SCPiiOsiM                    = SCName(C._SC_PII_OSI_M)
	SCTIovMax                    = SCName(C._SC_T_IOV_MAX)
	SCThreads                    = SCName(C._SC_THREADS)
	SCThreadSafeFunctions        = SCName(C._SC_THREAD_SAFE_FUNCTIONS)
	SCGetgrRSizeMax              = SCName(C._SC_GETGR_R_SIZE_MAX)
	SCGetpwRSizeMax              = SCName(C._SC_GETPW_R_SIZE_MAX)
	SCLoginNameMax               = SCName(C._SC_LOGIN_NAME_MAX)
	SCTtyNameMax                 = SCName(C._SC_TTY_NAME_MAX)
	SCThreadDestructorIterations = SCName(C._SC_THREAD_DESTRUCTOR_ITERATIONS)
	SCThreadKeysMax              = SCName(C._SC_THREAD_KEYS_MAX)
	SCThreadStackMin             = SCName(C._SC_THREAD_STACK_MIN)
	SCThreadThreadsMax           = SCName(C._SC_THREAD_THREADS_MAX)
	SCThreadAttrStackaddr        = SCName(C._SC_THREAD_ATTR_STACKADDR)
	SCThreadAttrStacksize        = SCName(C._SC_THREAD_ATTR_STACKSIZE)
	SCThreadPriorityScheduling   = SCName(C._SC_THREAD_PRIORITY_SCHEDULING)
	SCThreadPrioInherit          = SCName(C._SC_THREAD_PRIO_INHERIT)
	SCThreadPrioProtect          = SCName(C._SC_THREAD_PRIO_PROTECT)
	SCThreadProcessShared        = SCName(C._SC_THREAD_PROCESS_SHARED)
	SCNprocessorsConf            = SCName(C._SC_NPROCESSORS_CONF)
	SCNprocessorsOnln            = SCName(C._SC_NPROCESSORS_ONLN)
	SCPhysPages                  = SCName(C._SC_PHYS_PAGES)
	SCAvphysPages                = SCName(C._SC_AVPHYS_PAGES)
	SCAtexitMax                  = SCName(C._SC_ATEXIT_MAX)
	SCPassMax                    = SCName(C._SC_PASS_MAX)
	SCXopenVersion               = SCName(C._SC_XOPEN_VERSION)
	SCXopenXcuVersion            = SCName(C._SC_XOPEN_XCU_VERSION)
	SCXopenUnix                  = SCName(C._SC_XOPEN_UNIX)
	SCXopenCrypt                 = SCName(C._SC_XOPEN_CRYPT)
	SCXopenEnhI18N               = SCName(C._SC_XOPEN_ENH_I18N)
	SCXopenShm                   = SCName(C._SC_XOPEN_SHM)
	SC2CharTerm                  = SCName(C._SC_2_CHAR_TERM)
	SC2CVersion                  = SCName(C._SC_2_C_VERSION)
	SC2Upe                       = SCName(C._SC_2_UPE)
	SCXopenXpg2                  = SCName(C._SC_XOPEN_XPG2)
	SCXopenXpg3                  = SCName(C._SC_XOPEN_XPG3)
	SCXopenXpg4                  = SCName(C._SC_XOPEN_XPG4)
	SCCharBit                    = SCName(C._SC_CHAR_BIT)
	SCCharMax                    = SCName(C._SC_CHAR_MAX)
	SCCharMin                    = SCName(C._SC_CHAR_MIN)
	SCIntMax                     = SCName(C._SC_INT_MAX)
	SCIntMin                     = SCName(C._SC_INT_MIN)
	SCLongBit                    = SCName(C._SC_LONG_BIT)
	SCWordBit                    = SCName(C._SC_WORD_BIT)
	SCMbLenMax                   = SCName(C._SC_MB_LEN_MAX)
	SCNzero                      = SCName(C._SC_NZERO)
	SCSsizeMax                   = SCName(C._SC_SSIZE_MAX)
	SCScharMax                   = SCName(C._SC_SCHAR_MAX)
	SCScharMin                   = SCName(C._SC_SCHAR_MIN)
	SCShrtMax                    = SCName(C._SC_SHRT_MAX)
	SCShrtMin                    = SCName(C._SC_SHRT_MIN)
	SCUcharMax                   = SCName(C._SC_UCHAR_MAX)
	SCUintMax                    = SCName(C._SC_UINT_MAX)
	SCUlongMax                   = SCName(C._SC_ULONG_MAX)
	SCUshrtMax                   = SCName(C._SC_USHRT_MAX)
	SCNlArgmax                   = SCName(C._SC_NL_ARGMAX)
	SCNlLangmax                  = SCName(C._SC_NL_LANGMAX)
	SCNlMsgmax                   = SCName(C._SC_NL_MSGMAX)
	SCNlNmax                     = SCName(C._SC_NL_NMAX)
	SCNlSetmax                   = SCName(C._SC_NL_SETMAX)
	SCNlTextmax                  = SCName(C._SC_NL_TEXTMAX)
	SCXbs5Ilp32Off32             = SCName(C._SC_XBS5_ILP32_OFF32)
	SCXbs5Ilp32Offbig            = SCName(C._SC_XBS5_ILP32_OFFBIG)
	SCXbs5Lp64Off64              = SCName(C._SC_XBS5_LP64_OFF64)
	SCXbs5LpbigOffbig            = SCName(C._SC_XBS5_LPBIG_OFFBIG)
	SCXopenLegacy                = SCName(C._SC_XOPEN_LEGACY)
	SCXopenRealtime              = SCName(C._SC_XOPEN_REALTIME)
	SCXopenRealtimeThreads       = SCName(C._SC_XOPEN_REALTIME_THREADS)
	SCAdvisoryInfo               = SCName(C._SC_ADVISORY_INFO)
	SCBarriers                   = SCName(C._SC_BARRIERS)
	SCBase                       = SCName(C._SC_BASE)
	SCCLangSupport               = SCName(C._SC_C_LANG_SUPPORT)
	SCCLangSupportR              = SCName(C._SC_C_LANG_SUPPORT_R)
	SCClockSelection             = SCName(C._SC_CLOCK_SELECTION)
	SCCputime                    = SCName(C._SC_CPUTIME)
	SCThreadCputime              = SCName(C._SC_THREAD_CPUTIME)
	SCDeviceIo                   = SCName(C._SC_DEVICE_IO)
	SCDeviceSpecific             = SCName(C._SC_DEVICE_SPECIFIC)
	SCDeviceSpecificR            = SCName(C._SC_DEVICE_SPECIFIC_R)
	SCFdMgmt                     = SCName(C._SC_FD_MGMT)
	SCFifo                       = SCName(C._SC_FIFO)
	SCPipe                       = SCName(C._SC_PIPE)
	SCFileAttributes             = SCName(C._SC_FILE_ATTRIBUTES)
	SCFileLocking                = SCName(C._SC_FILE_LOCKING)
	SCFileSystem                 = SCName(C._SC_FILE_SYSTEM)
	SCMonotonicClock             = SCName(C._SC_MONOTONIC_CLOCK)
	SCMultiProcess               = SCName(C._SC_MULTI_PROCESS)
	SCSingleProcess              = SCName(C._SC_SINGLE_PROCESS)
	SCNetworking                 = SCName(C._SC_NETWORKING)
	SCReaderWriterLocks          = SCName(C._SC_READER_WRITER_LOCKS)
	SCSpinLocks                  = SCName(C._SC_SPIN_LOCKS)
	SCRegexp                     = SCName(C._SC_REGEXP)
	SCRegexVersion               = SCName(C._SC_REGEX_VERSION)
	SCShell                      = SCName(C._SC_SHELL)
	SCSignals                    = SCName(C._SC_SIGNALS)
	SCSpawn                      = SCName(C._SC_SPAWN)
	SCSporadicServer             = SCName(C._SC_SPORADIC_SERVER)
	SCThreadSporadicServer       = SCName(C._SC_THREAD_SPORADIC_SERVER)
	SCSystemDatabase             = SCName(C._SC_SYSTEM_DATABASE)
	SCSystemDatabaseR            = SCName(C._SC_SYSTEM_DATABASE_R)
	SCTimeouts                   = SCName(C._SC_TIMEOUTS)
	SCTypedMemoryObjects         = SCName(C._SC_TYPED_MEMORY_OBJECTS)
	SCUserGroups                 = SCName(C._SC_USER_GROUPS)
	SCUserGroupsR                = SCName(C._SC_USER_GROUPS_R)
	SC2Pbs                       = SCName(C._SC_2_PBS)
	SC2PbsAccounting             = SCName(C._SC_2_PBS_ACCOUNTING)
	SC2PbsLocate                 = SCName(C._SC_2_PBS_LOCATE)
	SC2PbsMessage                = SCName(C._SC_2_PBS_MESSAGE)
	SC2PbsTrack                  = SCName(C._SC_2_PBS_TRACK)
	SCSymloopMax                 = SCName(C._SC_SYMLOOP_MAX)
	SCStreams                    = SCName(C._SC_STREAMS)
	SC2PbsCheckpoint             = SCName(C._SC_2_PBS_CHECKPOINT)
	SCV6Ilp32Off32               = SCName(C._SC_V6_ILP32_OFF32)
	SCV6Ilp32Offbig              = SCName(C._SC_V6_ILP32_OFFBIG)
	SCV6Lp64Off64                = SCName(C._SC_V6_LP64_OFF64)
	SCV6LpbigOffbig              = SCName(C._SC_V6_LPBIG_OFFBIG)
	SCHostNameMax                = SCName(C._SC_HOST_NAME_MAX)
	SCTrace                      = SCName(C._SC_TRACE)
	SCTraceEventFilter           = SCName(C._SC_TRACE_EVENT_FILTER)
	SCTraceInherit               = SCName(C._SC_TRACE_INHERIT)
	SCTraceLog                   = SCName(C._SC_TRACE_LOG)
	SCLevel1IcacheSize           = SCName(C._SC_LEVEL1_ICACHE_SIZE)
	SCLevel1IcacheAssoc          = SCName(C._SC_LEVEL1_ICACHE_ASSOC)
	SCLevel1IcacheLinesize       = SCName(C._SC_LEVEL1_ICACHE_LINESIZE)
	SCLevel1DcacheSize           = SCName(C._SC_LEVEL1_DCACHE_SIZE)
	SCLevel1DcacheAssoc          = SCName(C._SC_LEVEL1_DCACHE_ASSOC)
	SCLevel1DcacheLinesize       = SCName(C._SC_LEVEL1_DCACHE_LINESIZE)
	SCLevel2CacheSize            = SCName(C._SC_LEVEL2_CACHE_SIZE)
	SCLevel2CacheAssoc           = SCName(C._SC_LEVEL2_CACHE_ASSOC)
	SCLevel2CacheLinesize        = SCName(C._SC_LEVEL2_CACHE_LINESIZE)
	SCLevel3CacheSize            = SCName(C._SC_LEVEL3_CACHE_SIZE)
	SCLevel3CacheAssoc           = SCName(C._SC_LEVEL3_CACHE_ASSOC)
	SCLevel3CacheLinesize        = SCName(C._SC_LEVEL3_CACHE_LINESIZE)
	SCLevel4CacheSize            = SCName(C._SC_LEVEL4_CACHE_SIZE)
	SCLevel4CacheAssoc           = SCName(C._SC_LEVEL4_CACHE_ASSOC)
	SCLevel4CacheLinesize        = SCName(C._SC_LEVEL4_CACHE_LINESIZE)
	SCIpv6                       = SCName(C._SC_IPV6)
	SCRawSockets                 = SCName(C._SC_RAW_SOCKETS)
	SCV7Ilp32Off32               = SCName(C._SC_V7_ILP32_OFF32)
	SCV7Ilp32Offbig              = SCName(C._SC_V7_ILP32_OFFBIG)
	SCV7Lp64Off64                = SCName(C._SC_V7_LP64_OFF64)
	SCV7LpbigOffbig              = SCName(C._SC_V7_LPBIG_OFFBIG)
	SCSsReplMax                  = SCName(C._SC_SS_REPL_MAX)
	SCTraceEventNameMax          = SCName(C._SC_TRACE_EVENT_NAME_MAX)
	SCTraceNameMax               = SCName(C._SC_TRACE_NAME_MAX)
	SCTraceSysMax                = SCName(C._SC_TRACE_SYS_MAX)
	SCTraceUserEventMax          = SCName(C._SC_TRACE_USER_EVENT_MAX)
	SCXopenStreams               = SCName(C._SC_XOPEN_STREAMS)
	SCThreadRobustPrioInherit    = SCName(C._SC_THREAD_ROBUST_PRIO_INHERIT)
	SCThreadRobustPrioProtect    = SCName(C._SC_THREAD_ROBUST_PRIO_PROTECT)
)
